### ISSUE TITLE
Fix Junit Reporter action permission issues

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-e2e#186]
There are errors coming from junit reporter action regarding workflow permissions.
```
 windows (10, 22h2-ent)
❌ Failed to create checks using the provided token. (HttpError: Resource not accessible by integration - https://docs.github.com/rest/checks/runs#create-a-check-run)
```

fix is to add:
```
  windows:
    name: ${{ matrix.windows-version }} - Debug
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
```
