### ISSUE TITLE
Switch to using podman setup.exe installer as a default podman installation method

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-e2e#240]
Right now we are using zip archive to install podman for the windows workflows. This works quite ok for wsl provider but for hyperv virtualization provider we are encountering problem with `gvproxy` as seen in #228. 

Right now the podman zip url parameter from the workflows:
```
      podman_remote_url:
        default: 'https://github.com/containers/podman/releases/download/v5.2.0/podman-remote-release-windows_amd64.zip'
        description: 'podman remote zip'
        type: string
        required: true
```

Can use zip url to installs podman on path. With use of `pde2e-podman:v0.0.2-windows` image version `setup.exe` is also supported. Installation of the podman binarines via the installer is the only way to use hyperv as podman machine virtualization provider.
